run:
  timeout: 3m
  tests: true
  skip-dirs:
    - mocks
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    - gofmt # Use make fmt
    - gocyclo
    - dupl
    - funlen
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  staticcheck:
    checks: ["all"]
issues:
  exclude-dirs:
    - mocks
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
